# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'OneOtwo' do
    pod 'AFNetworking'
    pod 'SDWebImage'
    pod 'MJRefresh'
    pod 'YYModel'
    pod 'Masonry'
    pod 'MBProgressHUD'
end
